config/routes.rb
Rails.application.routes.draw do
  get     '/home',                      to: 'student#show'
  get     '/login',                     to: 'sessions#new'
  post    '/login',                     to: 'sessions#create'
  delete  '/logout',                    to: 'sessions#destroy'
  get     '/labs/sync',                 to: 'labs#sync',  as: :sync_labs
  root    'sessions#new'

  resources :semesters, only: [:show, :index]

  resources :courses_semesters, only: [:show, :index, :new, :create] do
    resources :labs, only: [:show, :index] do
      resources :labs_students, only: [:index, :show]
    end
    resources :projects, only: [:index, :show]
  end

  resources :instructors, only: [:index, :show] do
    resources :labs, only: [:index, :show] do
      resources :labs_students_imports, only: [:new, :create]
    end
  end

  resources :students, only: [:index, :show] do
    resources :labs do
      resources :labs_students, only: [:create]
    end
  end

  resources :students_imports, only: [:new, :create]
  resources :labs_imports, only: [:new, :create]
end

app/models/semester.rb
class Semester < ApplicationRecord
  has_many :courses_semesters
  has_many :courses, through: :courses_semesters

  validates :label, presence: true, uniqueness: true
end

app/controllers/semesters_controller.rb
class SemestersController < ApplicationController
  include SemestersHelper

  def index
    @semester = read_current_semester

    if @semester.nil?
      flash[:danger] = 'Opa, Murphyho zákony zaúradovali. Skúste neskôr'
    else
      if @semester.new_record?
        unless @semester.save
          flash[:danger] = 'Záznamy sa nepodarilo aktualizovať'
        end
      end
    end

    @semesters = Semester.all
  end

  def show
    @semester = Semester.find(params[:id])
    @courses_semesters = CoursesSemester.where(semester_id: params[:id])
  end
end

app/helpers/semesters_helper.rb
require 'open-uri'

module SemestersHelper
  def read_current_semester
    doc = Nokogiri::HTML(open('http://is.stuba.sk/student/harmonogram.pl?fakulta=70;lang=sk'))
    rows = doc.xpath('//table/tbody/tr/td/small/b')
    current = rows.first.at_xpath('text()').to_s
    @semester = current.split('-').first.strip
    Semester.find_or_create_by(label: @semester)
  end

  def current_semester
    @semester ||= Semester.last
  end
end

app/views/semesters/index.html.erb
<% title = 'Semestre' %>
<% provide :title, title %>

<section class="content-header">
  <h1><%= title %></h1>
  <%= render_breadcrumb %>
</section>

<section class="content">
  <% if @semesters.present? %>
    <div class="box box-success">
      <div class="box-header">
        <h2>Semestre</h2>
      </div>
      <div class="box-body table-responsive no-padding">
        <table class="table table-hover">
          <tbody>
          <% @semesters.each do |semester| %>
          <tr>
            <td>
              <%= link_to semester.label, semester_path(semester) %>
            </td>
          </tr>
          <% end %>
          </tbody>
        </table>
      </div>
    </div>
  <% else %>
    Aplikácia ešte nebola nasadené počas semestra.
  <% end %>
</section>

app/views/semesters/show.html.erb
<% title = @semester.label %>
<% provide :title, title %>

<% breadcrumb_add 'Semestre', semesters_path %>

<section class="content-header">
  <h1><%= title %></h1>
  <%= render_breadcrumb %>
</section>

<section class="content">
  <% if current_user.instance_of? Instructor %>
    <%= link_to new_courses_semester_path, class: 'btn btn-success' do %>
      <i class="glyphicon glyphicon-plus"></i> Pridať predmet
    <% end %>
  <% end %>
  
  <% if @courses_semesters.present? %>
    <div class="box box-success">
      <div class="box-body table-responsive">
        <table class="table">
          <thead>
            <tr>
              <th>Predmet</th>
              <th>Garant</th>
              <th>Late days</th>
            </tr>
          </thead>
          <tbody>
            <% @courses_semesters.each do |course_semester| %>
            <tr>
              <td>
                <%= link_to courses_semester_path(course_semester) do %>
                  <%= course_semester.course.name %>
                <% end %>
              </td>
              <td><%= course_semester.supervisor %></td>
              <td><%= course_semester.late_days %></td>
            </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  <% end %>
</section>