config/routes.rb
Rails.application.routes.draw do
  get     '/home',                      to: 'student#show'
  get     '/login',                     to: 'sessions#new'
  post    '/login',                     to: 'sessions#create'
  delete  '/logout',                    to: 'sessions#destroy'
  get     '/labs/sync',                 to: 'labs#sync',  as: :sync_labs
  root    'sessions#new'

  resources :semesters, only: [:show, :index]

  resources :courses_semesters, only: [:show, :index, :new, :create] do
    resources :labs, only: [:show, :index] do
      resources :labs_students, only: [:index, :show]
    end
    resources :projects, only: [:index, :show]
  end

  resources :instructors, only: [:index, :show] do
    resources :labs, only: [:index, :show] do
      resources :labs_students_imports, only: [:new, :create]
    end
  end

  resources :students, only: [:index, :show] do
    resources :labs do
      resources :labs_students, only: [:create]
    end
  end

  resources :students_imports, only: [:new, :create]
  resources :labs_imports, only: [:new, :create]
end

app/models/student.rb
class Student < ApplicationRecord
  self.primary_key = :ais_id

  has_many :projects_students
  has_many :projects, through: :projects_students
  has_many :labs_students
  has_many :labs, through: :labs_students

  validates :name, presence: true, format: { without: /[0-9]/, message: 'Meno neobsahuje čísla' }
  validates :ais_id, presence: true, uniqueness: true, format: { with: /\A\d+\z/, message: 'AIS id obsahuje len čísla' }

  def self.import(file)
    sheet = open_spreadsheet(file)
    sheet.row(1)
    sheet.each(ais_id: 'C', name: 'B').each do |hash|
      puts hash.inspect
    end
   end

  def self.open_spreadsheet(file)
    case File.extname(file.original_filename)
    when '.csv' then Csv.new(file.path, nil, :ignore)
    when '.xls' then Excel.new(file.path, nil, :ignore)
    when '.xlsx' then Excelx.new(file.path, nil, :ignore)
    else raise "Neznámy typ súboru: #{file.original_filename}"
    end
  end

  def self.get(id)
    Student.find_by(ais_id: id)
  end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController

  include TuringHelper

  def index
    @students = Student.all.order(:name)
    @title = 'Študenti'
  end

  def show
      @title = 'Moje Late Days'
      ais_id = current_user.ais_id
      latedays = get_projects_for_student(ais_id)

      unless latedays.nil?
        @projects = latedays[ais_id.to_s]

        unless @projects.nil?
          @projects.each do |project|
            Project.insert_from_turing_data(project, ais_id, current_semester.id)
          end
        end
      end
  end

  def import
    Student.import(params[:file])
    flash[:success] = 'Študenti pridaní'
    redirect_to students_path
  end

end

app/views/students/index.html.erb
<% provide :title, @title %>

<section class="content-header">
  <h1><%= @title %></h1>
  <%= render_breadcrumb %>
</section>

<section class="content">
  <%= link_to new_students_import_path, class: 'btn btn-success' do %>
    <i class="glyphicon glyphicon-import"></i> Import študentov
  <% end %>

  <% if @students.present? %>
    <div class="box box-success">
      <div class="box-body table-responsive no-padding">
      <table class="table table-hover">
        <thead>
          <tr>
            <th>Meno</th>
            <th>Upraviť</th>
          </tr>
        </thead>
        <tbody>
        <% @students.each do |student| %>
          <tr>
            <td><%= student.name %></td>
            <td>
              <% if student.ais_id == current_user.ais_id %>
                <%= link_to edit_student_path(student), class: 'text-success' do %>
                  <i class="glyphicon glyphicon-pencil"></i>
                <% end %>
              <% end %>
            </td>
          </tr>
        <% end %>
        </tbody>
      </table>
      </div>
    </div>
  <% end %>
</section>

app/views/students/show.html.erb
<% provide :title, @title %>

<section class="content-header">
  <h1><%= @title %></h1>
  <%= render_breadcrumb %>
</section>

<section class="content">
  <% if @projects.present? %>
    <div class="box box-success">
      <div class="box-body table-responsive no-padding">
        <table class="table table-hover">
          <thead>
          <tr>
            <th>Predmet</th>
            <th>Projekt</th>
            <th>Minuté late days</th>
          </tr>
          </thead>
          <tbody>
          <% @projects.each do |project| %>
            <tr>
              <td><%= project['course'] %></td>
              <td><%= project['assignment'] %></td>
              <td><%= days_between project['submission_date'], project['deadline'] %></td>
            </tr>
          <% end %>
          </tbody>
        </table>
      </div>
    </div>
  <% end %>
</section>