config/routes.rb
Rails.application.routes.draw do
  get     '/home',                      to: 'student#show'
  get     '/login',                     to: 'sessions#new'
  post    '/login',                     to: 'sessions#create'
  delete  '/logout',                    to: 'sessions#destroy'
  get     '/labs/sync',                 to: 'labs#sync',  as: :sync_labs
  root    'sessions#new'

  resources :semesters, only: [:show, :index]

  resources :courses_semesters, only: [:show, :index, :new, :create] do
    resources :labs, only: [:show, :index] do
      resources :labs_students, only: [:index, :show]
    end
    resources :projects, only: [:index, :show]
  end

  resources :instructors, only: [:index, :show] do
    resources :labs, only: [:index, :show] do
      resources :labs_students_imports, only: [:new, :create]
    end
  end

  resources :students, only: [:index, :show] do
    resources :labs do
      resources :labs_students, only: [:create]
    end
  end

  resources :students_imports, only: [:new, :create]
  resources :labs_imports, only: [:new, :create]
end

app/models/instructor.rb
class Instructor < ApplicationRecord
  self.primary_key = :ais_id

  has_many :labs
  has_many :courses_semesters, through: :labs, dependent: :delete_all

  validates :name, presence: true, format: {
    without: /[0-9]/, message: 'Meno neobsahuje čísla'
  }

  validates :ais_id, presence: true, uniqueness: true, format: {
    with: /\A\d+\z/, message: 'AIS id obsahuje len čísla'
  }

  def self.get(id)
    Instructor.find_by(ais_id: id)
  end
end

app/controllers/instructors_controller.rb
class InstructorsController < ApplicationController
  def index
    @instructors = Instructor.all.order(:name)
    @title = 'Cvičiaci'
  end

  def show
    @instructor = Instructor.find(params[:id])
    @courses_semester = CoursesSemester.find_by(params[:courses_semester_id])
    @labs = @instructor.labs
  end
end

app/views/instructors/index.html.erb
<% provide :title, @title %>

<section class="content-header">
  <h1><%= @title %></h1>
  <%= render_breadcrumb %>
</section>

<section class="content">
  <% if @instructors.present? %>
    <div class="box box-success">
      <div class="box-body table-responsive no-padding">
        <table class="table table-hover">
          <thead>
            <th>Meno</th>
            <th>Zobraziť v AISe</th>
          </thead>
          <tbody>
            <% @instructors.each do |instr| %>
              <% ais_info_link = "https://is.stuba.sk/auth/lide/clovek.pl?id=" + instr.id.to_s + ";" %>
              <tr>
                <td><%= link_to instr.name, instructor_path(instr) %></td>
                <td>
                  <a href="<%= ais_info_link %>" target="_blank" class="text-success">
                    <span class="glyphicon glyphicon-link"></span>
                  </a>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  <% end %>
</section>

app/views/instructors/show.html.erb
<% provide :title, @instructor.name %>
<% breadcrumb_add 'Cvičiaci', instructors_path %>

<section class="content-header">
    <h1><%= @instructor.name %></h1>
    <%= render_breadcrumb %>
</section>

<section class="content">
  <% ais_info_link = "https://is.stuba.sk/auth/lide/clovek.pl?id=" + @instructor.id.to_s + ";" %>
  <a href="<%= ais_info_link %>" target="_blank" class="btn btn-large btn-success">Profil v AISe</a>

  <% if @labs.present? %>
    <div class="box box-success">
      <div class="box-body table-responsive">
        <table class="table table-hover">
          <thead>
            <th>Predmet</th>
            <th colspan="2"></th>
          </thead>
          <tbody>
            <% @labs.each do |lab| %>
            <tr>
              <td>
                <%= link_to courses_semester_path(lab.courses_semester_id) do %>
                  <%= lab.courses_semester.course.name %>
                <% end %>
              </td>
              <td>
                <%= link_to instructor_lab_path(lab.instructor_id, lab) do %>
                  <%= lab.day.capitalize %>,
                  <%= format_time lab.start_at %> -
                  <%= lab_end_time lab %>
                <% end %>
              </td>
            </tr>
            <% end %>
          </tbody>
         </table>
       </div>
     </div>
   <% else %>
    <p class="clearfix" style="margin-top: 2em">
      Cvičiaci nemá pridelené nijaké cvičenia.
    </p>
  <% end %>
</section>