config/routes.rb
Rails.application.routes.draw do
  get     '/home',                      to: 'student#show'
  get     '/login',                     to: 'sessions#new'
  post    '/login',                     to: 'sessions#create'
  delete  '/logout',                    to: 'sessions#destroy'
  get     '/labs/sync',                 to: 'labs#sync',  as: :sync_labs
  root    'sessions#new'

  resources :semesters, only: [:show, :index]

  resources :courses_semesters, only: [:show, :index, :new, :create] do
    resources :labs, only: [:show, :index] do
      resources :labs_students, only: [:index, :show]
    end
    resources :projects, only: [:index, :show]
  end

  resources :instructors, only: [:index, :show] do
    resources :labs, only: [:index, :show] do
      resources :labs_students_imports, only: [:new, :create]
    end
  end

  resources :students, only: [:index, :show] do
    resources :labs do
      resources :labs_students, only: [:create]
    end
  end

  resources :students_imports, only: [:new, :create]
  resources :labs_imports, only: [:new, :create]
end

app/models/lab.rb
class Lab < ApplicationRecord
  enum day: %i[pondelok utorok streda štvrtok piatok]
  belongs_to :instructor
  belongs_to :courses_semester

  validates :duration, numericality: { only_integer: true }

  def self.get_students_for_instructor(instructor_id, semester_id)
    courses = CoursesSemester.where(semester_id: semester_id)

    courses.each do |course|
      Lab.where(instructor_id: instructor_id, course_id: course.id)
    end
  end

  def self.get_projects(lab)
    Project.where(courses_semester_id: lab.courses_semester_id)
  end
end

app/controllers/labs_controller.rb
class LabsController < ApplicationController
  include LabsHelper

  helper_method :students_lab_project

  def show
    @lab = Lab.find(params[:id])
    @projects = Lab.get_projects(@lab)
  end

  def index
    @lab = Lab.find_by(courses_semester_id: params[:courses_semesters_id])
    @courses_semester = CoursesSemester.find(params[:courses_semester_id])
    @title = @courses_semester.course.name
  end

  def sync
    @course = Course.find(params[:format])
    get_labs @course, current_semester
    redirect_to :back
  end

  def students_lab_project(lab, project)
    LabsStudent.students_for_lab_and_project(lab, project)
  end

end

app/helpers/labs_helper.rb
module LabsHelper
  def get_labs(course, semester)
    rows = parse_labs course, semester

    if rows.nil?
      flash[:warning] = 'Nenašli sa nijaké cvičenia pre daný predmet.'
      return
    end

    courses_semester ||= CoursesSemester.select(:id).where(course_id: course, semester_id: semester).first
    labs ||= []

    rows.each do |row|
      day = get_day row.at('td[1]').text.strip
      start = row.at('td[2]').text.strip
      ending = row.at('td[3]').text.strip
      type = row.at('td[5]').text.strip
      duration = calc_duration start, ending
      instr_name = row.at('td[7]').text
      instr_fname = instr_name.split('.').first.strip
      instr_lname = instr_name.split('.').last.strip
      name = instr_fname + '% ' + instr_lname

      instructor = Instructor.select(:ais_id).where('name LIKE ?', name).first

      if instructor.nil?
        href = row.at('td[7] a').attributes['href'].value
        ais = href.slice(href.index('=') + 1..href.index(';') - 1)
        instructor = Instructor.create(ais_id: ais, name: instr_name)
      end

      next unless type == 'Cvičenie'
      start_at = lab_start start

      labs << Lab.where(
        day: day,
        start_at: start_at,
        duration: duration,
        courses_semester_id: courses_semester.id,
        instructor_id: instructor.ais_id
      ).first_or_create
    end
    flash[:success] = 'Cvičenia aktualizované.'
  end

  def parse_labs(course, semester)
    mechanize = Mechanize.new

    url = 'http://is.stuba.sk/katalog/rozvrhy_view.pl?konf=1;f=70;lang=sk'
    page = mechanize.get(url)
    td = page.at("table tbody tr td small:contains('#{semester.label}')")

    return if td.nil?

    row = td.parent

    return if row.nil?

    table = row.parent
    value = table.at('td small input').attributes['value'].value
    form = page.forms.first
    form.checkbox(value: value).check

    page = form.submit
    form = page.forms.first
    select_option form, 'predmet', course.abbr
    select_option form, 'format', 'Zoznam rozvrhových akcii'
    view = form.button_with(name: 'zobraz')

    page = form.submit(view)
    doc = Nokogiri::HTML(page.body)
    table = doc.css('table').first
    table.css('tbody tr')
  end

  def select_option(form, field_name, text)
    value = nil
    form.field_with(name: field_name).options.each do |o|
      if o.text.start_with? text
        value = o
        break
      end
    end
    raise ArgumentError, "No option with text #{text} in field '#{field_name}'" unless value
    form.field_with(name: field_name).value = value
  end

  def get_day(day)
    case day
    when 'Po'
      0
    when 'Ut'
      1
    when 'St'
      2
    when 'Št'
      3
    when 'Pi'
      4
    else
      0
    end
  end

  def calc_duration(start, ending)
    start_hour = start.split('.').first.to_i
    start_minutes = start.split('.').last.to_i

    ending_hour = ending.split('.').first.to_i
    ending_minutes = ending.split('.').last.to_i

    (60 * (ending_hour - start_hour) + (ending_minutes - start_minutes)) / 50
  end

  def lab_start(start)
    hour = start.split('.').first.to_i
    minute = start.split('.').last.to_i
    "#{hour}:#{minute}"
  end
end

app/views/labs/show.html.erb
<% instructor = @lab.instructor %>
<% title = @lab.courses_semester.course.name%>
<% provide :title, title %>

<section class="content-header">
  <h1>
    <%= title %>:
    <%= @lab.day.capitalize %>, <%= format_time @lab.start_at %> - <%= lab_end_time @lab %>
  </h1>
  <%= render_breadcrumb %>
</section>

<section class="content">
  <% if current_user.ais_id == instructor.ais_id %>
    <%= link_to new_instructor_lab_labs_students_import_url(instructor, @lab), class: 'btn btn-success' do %>
      <i class="glyphicon glyphicon-import"></i> Importovať študentov
    <% end %>
  <% end %>

  <% if current_user.instance_of? Student %>
    <%= link_to student_lab_labs_students_path(current_user.ais_id, @lab), method: 'post', class: 'btn btn-success' do %>
      <i class="glyphicon glyphicon-log-in"></i> Registrovať sa
    <% end %>
  <% end %>

  <% if current_user.instance_of? Instructor %>
    <% if @projects.present? %>
      <% @projects.each do |project| %>
      <div class="box box-success">
        <div class="box-header">
          <h3 class="box-title"><%= project.assignment.name %></h3>
        </div>
        <div class="box-content table-responsive">
          <table class="table table-hover">
            <thead>
            <tr>
              <th>Študent</th>
              <th>Počet late days</th>
            </tr>
            </thead>
            <tbody>
              <% students = students_lab_project(@lab, project) %>
              <% students.each do |student| %>
                <tr>
                  <td><%= student.student.name %></td>
                  <td><%= student.spent_late_days %></td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
      <% end %>
    <% end %>
  <% end %>
</section>